<!DOCTYPE html>
<html lang="<?php echo SHORT_LOCALE; ?>">
<head>
    <title><?php echo SITE_NAME; ?> :: <?php echo $this->_i18n->getPageTitle(); ?></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <meta name="description" content="<?php echo $this->_i18n->getGlobalElemText('site_description'); ?>" />
    <meta name="keywords" content="<?php echo $this->_i18n->getGlobalElemText('keywords'); ?>" />
    <meta name="revisit-after" content="1 days" />
    <meta name="robots" content="all" />
    <!-- <link rel="icon" type="image/ico" href="favicon.ico" /> -->
    <!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="favicon.ico" /><![endif]-->
    <link rel="stylesheet" type="text/css" href="media/css/base.css" />
    <!--[if lt IE 9]><script type="text/javascript" src="http<?php if (IS_HTTPS) echo 's'; ?>://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
<span id="jsIncludes"></span>
<header id="header">
    <div id="logo"><a href="<?php echo BASE_URL; ?>"><img src="media/img/logo.jpg" alt="LOGO SITE" /></a></div>
</header>
<div id="content">
